### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by doraithodla** [ashsih101/ThinkPython#1]
There is a document called PEP8 that describes how Python programs should be formatted. You can read it whenever you find some time (it is kind of a boring document to read). However, download the PEP8 utlity and run your sources through it and correct the formatting errors. Here are a couple. 
1. Spacecs around assignment operators
2. Spaces around arithmetic operators

**Comment by PandaWhoCodes** [comment]
Code Reformatted. Please check if there are anymore of such formatting errors

**Comment by doraithodla** [comment]
It is not worth checking manually. You can run pep8 and check it. https://pypi.python.org/pypi/pep8
